"Change directory of .swp files
set directory=$HOME/.vim/swp//

"Convert tabs to spaces
set tabstop=2
set shiftwidth=2
set expandtab

"Open buffers without saving
set hidden

"Make splits more natural
set splitbelow
set splitright

"Show the 80 char line
set colorcolumn=80

"Mappings

"Command key
nnoremap ; :
"Easier split navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
nnoremap _ <C-W>_
"Easier tab navigation
map <Tab> :bnext<CR>
map <S-Tab> :bprevious<CR>
"Kill buffer
nnoremap <C-k> :bd<CR>
"Clear search results
nnoremap <C-\> :noh<return>
"Open file search
nnoremap <C-P> :Files<return>
"Open ripgrep
nnoremap <C-F> :Rg<return>
"Open tag search
nnoremap <C-G> :Tags<return>

"Line numbers
set number

" Syntax highlighting
syntax on
colorscheme nord

" Airline
let g:airline_powerline_fonts = 1
"let g:airline_theme = "256_noir"
let g:airline#extensions#tabline#enabled = 1
"let g:shades_of_purple_airline = 1
"let g:airline_theme='shades_of_purple'
let python_highlight_all = 1
"let base16colorspace=256  " Access colors present in 256 colorspace

" C++
"let g:cpp_class_scope_highlight = 1
"let g:cpp_member_variable_highlight = 1
"let g:cpp_class_decl_highlight = 1
"let g:cpp_posix_standard = 1
"let g:cpp_experimental_template_highlight = 1
"let g:cpp_concepts_highlight = 1

" Haskell
let g:haskell_enable_quantification = 1   " to enable highlighting of `forall`
let g:haskell_enable_recursivedo = 1      " to enable highlighting of `mdo` and `rec`
let g:haskell_enable_arrowsyntax = 1      " to enable highlighting of `proc`
let g:haskell_enable_pattern_synonyms = 1 " to enable highlighting of `pattern`
let g:haskell_enable_typeroles = 1        " to enable highlighting of type roles
let g:haskell_enable_static_pointers = 1  " to enable highlighting of `static`
let g:haskell_backpack = 1                " to enable highlighting of backpack keywords

" LSP configuration
if executable('haskell-language-server')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'haskell-language-server',
        \ 'cmd': {server_info->['haskell-language-server', '--lsp']},
        \ 'allowlist': ['haskell'],
        \ })
endif

function! s:on_lsp_buffer_enabled() abort
    setlocal omnifunc=lsp#complete
    setlocal signcolumn=yes
    if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
    nmap <buffer> gd <plug>(lsp-definition)
    nmap <buffer> gs <plug>(lsp-document-symbol-search)
    nmap <buffer> gS <plug>(lsp-workspace-symbol-search)
    nmap <buffer> gr <plug>(lsp-references)
    nmap <buffer> gt <plug>(lsp-type-definition)
    nmap <buffer> <leader>rn <plug>(lsp-rename)
    nmap <buffer> [g <plug>(lsp-previous-diagnostic)
    nmap <buffer> ]g <plug>(lsp-next-diagnostic)
    nmap <buffer> K <plug>(lsp-hover)
    nnoremap <buffer> <expr><c-f> lsp#scroll(+4)
    nnoremap <buffer> <expr><c-d> lsp#scroll(-4)
endfunction

augroup lsp_install
    au!
    " call s:on_lsp_buffer_enabled only for languages that has the server registered.
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END
